# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "openamp-layer"
BBFILE_PATTERN_openamp-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_openamp-layer = "5"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_openamp-layer = "1"

# meta-openamp upstream master branch supports:
# = POLICY ======== CURRENT RELEASE ===
# master            blacksail   YP 6.1 2026/10
# latest release    (same as LTS currently)
# LTS               wrynose     YP 6.0 2026/04
# LTS-1             scarthgap   YP 5.0 2024/04
#
# each LTS is also supported by its own named branch
# (but only while the poky version is supported upstream)
# the named branch will not receive new OpenAMP versions
#
LAYERSERIES_COMPAT_openamp-layer = "blacksail wrynose scarthgap"

# set layer path for this layer only
LAYER_PATH_openamp-layer = "${LAYERDIR}"

# Each vendor must be in the list below, can't add these dynamically based on
# layer availability as we can't promise layer order processing
# Each layer.inc file should use BBFILES_DYNAMIC and NOT BBFILES.
OPENAMP_VENDOR_INCLUDE = ""
OPENAMP_VENDOR_INCLUDE += "${LAYER_PATH_openamp-layer}/vendor/xilinx/layer.inc"

include ${OPENAMP_VENDOR_INCLUDE}
